### ISSUE TITLE
Problem: ubuntu clamav settings are not being honored 

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-clamav#4]
Although we try to set them in https://github.com/artefactual-labs/ansible-clamav/blame/master/tasks/ubuntu.yml#L18, the `/etc/clamd/scan.conf` file is not being updated.

Tested using Ubuntu 16.04/clamav-daemon 0.99.4+addedllvm-0ubuntu0.16.04.1

**Comment by mamedin** [comment]
@scollazo I can't reproduce the issue. I tested the `dev/select-socket-type` branch with Ubuntu 16.04/clamav-daemon 0.99.4+addedllvm-0ubuntu0.16.04.1.
